version: '1.0'

services:

  web:
    build: ./app
    ports:
      - 8004:8000

    command: >
      bash -c "export LC_ALL=C.UTF-8
      && export LANG=C.UTF-8
      && uvicorn main:app --host 0.0.0.0 --reload"
      
    volumes:
      - ./app:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./app
    
    command: celery worker --app=worker.celery --loglevel=info -P threads

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    volumes:
      - ./app:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

    
  dashboard:
    build: ./app
    command:  flower --app=worker.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker